server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/skillswap_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
# Laisse ces lignes si tu les as, elles sont utiles :
spring.jpa.show-sql=true